"""Add roles to the users table

Revision ID: ac07c91c4243
Revises: 811c92eeb469
Create Date: 2026-08-17 16:34:00.435557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac07c91c4243'
down_revision: Union[str, Sequence[str], None] = '811c92eeb469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'role')
    # ### end Alembic commands ###
