"""Add soft delete (delete_at column)

Revision ID: 811c92eeb469
Revises: 506a77d77550
Create Date: 2026-08-14 15:52:04.974329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811c92eeb469'
down_revision: Union[str, Sequence[str], None] = '506a77d77550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'deleted_at')
    # ### end Alembic commands ###
